ARG NET_IMAGE=8.0
ARG BUILD_CONFIGURATION=Debug
FROM mcr.microsoft.com/dotnet/aspnet:${NET_IMAGE} AS base
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:${NET_IMAGE} AS build
WORKDIR /src

COPY ["src/BuildingBlocks/Devspaces.Support/Devspaces.Support.csproj", "BuildingBlocks/Devspaces.Support/"]
COPY ["src/BuildingBlocks/EventBus/EventBus.Tests/EventBus.Tests.csproj", "BuildingBlocks/EventBus/EventBus.Tests/"]
COPY ["src/BuildingBlocks/EventBus/EventBus/EventBus.csproj", "BuildingBlocks/EventBus/EventBus/"]
COPY ["src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj", "BuildingBlocks/EventBus/EventBusRabbitMQ/"]
COPY ["src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj", "BuildingBlocks/EventBus/EventBusServiceBus/"]
COPY ["src/BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLogEF.csproj", "BuildingBlocks/EventBus/IntegrationEventLogEF/"]
COPY ["src/BuildingBlocks/Observability/Observability.csproj", "BuildingBlocks/Observability/"]
COPY ["src/BuildingBlocks/Shared.Kernel/Shared.Kernel.csproj", "BuildingBlocks/Shared.Kernel/"]
COPY ["src/BuildingBlocks/WebHostCustomization/WebHost.Customization/WebHost.Customization.csproj", "BuildingBlocks/WebHostCustomization/WebHost.Customization/"]
COPY ["src/Services/Company/Company.API/Company.API.csproj", "Services/Company/Company.API/"]
COPY ["Directory.Build.props", "./"]
COPY ["Directory.Packages.props", "./"]

RUN dotnet restore Services/Company/Company.API/Company.API.csproj -nowarn:msb3202,nu1503
COPY src .

WORKDIR "/src/Services/Company/Company.API"
RUN dotnet build "Company.API.csproj" --no-restore -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "Company.API.csproj" -c Debug -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Company.API.dll"]