apiVersion: apps/v1
kind: Deployment
metadata:
    name: company-api-deploy
    namespace: awc-ns
spec:
    replicas: 2
    selector:
        matchLabels:
            app: company-api
    template:
        metadata:
            namespace: awc-ns
            labels:
                app: company-api
        spec:
            containers:
              - name: company-api
                image: brthomasusa/company-api:latest
                imagePullPolicy: Always
                env:
                  - name: "ConnectionStrings__CompanyDb"
                    value: "Server=tcp:192.168.1.16,1433;Database=CompanyAPI;User Id=sa;Password=Info99Gum;TrustServerCertificate=True;"
                  - name: "ConnectionStrings__Redis"
                    value: "redis-svc:6379"
                  - name: "ASPNETCORE_ENVIRONMENT"
                    value: "Production"
                  - name: "ASPNETCORE_HTTP_PORTS"
                    value: "3000"
                resources:
                    requests:
                        cpu: "0.5"
                        memory: 100Mi
                    limits:
                        cpu: "2"
                        memory: 500Mi
                ports:
                  - containerPort: 3000
