apiVersion: v1
kind: Pod
metadata:
    name: company-api-pod
    labels:
        app: company-api
spec:
    containers:
      - name: company-api
        image: brthomasusa/company-api:latest
        imagePullPolicy: Always
        env:
          - name: "ConnectionStrings__CompanyDb"
            value: "Server=tcp:192.168.1.16,1433;Database=CompanyAPI;User Id=sa;Password=Info99Gum;TrustServerCertificate=True;"
          - name: "ConnectionStrings__Redis"
            value: "10.96.86.151:6379"
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Productions"
          - name: "ASPNETCORE_HTTP_PORTS"
            value: "3000"
        resources:
            requests:
                cpu: 100m
                memory: 100Mi
            limits:
                cpu: 200m
                memory: 200Mi
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: company-api-svc
spec:
    type: LoadBalancer
    ports:
      - name: company-api-url
        protocol: TCP
        port: 3000
        targetPort: 3000
    selector:
        app: company-api
---


