apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-gateway
  labels:
    app: web-gateway
spec:
  selector:
    matchLabels:
      app: web-gateway
  template:
    metadata:
      labels:
        app: web-gateway
    spec:
      containers:
      - name: web-gateway
        image: brthomasusa/web-gateway:latest
        imagePullPolicy: Always
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Productions"
        - name: "ASPNETCORE_HTTP_PORTS"
          value: "5259"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 5259
---
apiVersion: v1
kind: Service
metadata:
  name: web-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 5259
  selector:
    app: web-gateway
