services:

  redis:
    image: redis:latest

  company.api:
    image: company.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Company/Company.API/Dockerfile
    depends_on:
      - redis

  product.api:
    image: product.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Product/Product.API/Dockerfile

  web.gateway:
    image: web-gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Api.Gateway/Dockerfile
    depends_on:
      - company.api
      - product.api

  webui:
    image: webui:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebUI/Dockerfile
