# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.

services:

  redis:
    ports:
      - "6279:6379"
    command: --port 6279
    hostname: "redis"
    container_name: "redis"

  company.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3000
      - ConnectionStrings__CompanyDbAzure=Server=tcp:awc-db-server.database.windows.net,1433;Initial Catalog=company-api-db;Persist Security Info=False;User ID=awc-dba;Password=Info99Gum;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30
      - ConnectionStrings__Redis=redis:6279      
    ports:
      - "3000:80"
    extra_hosts:
      - "ubuntu-2404:192.168.1.16"
    hostname: "company-api-svc"
    container_name: "company-api-svc"

  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3100
      - ConnectionStrings__CompanyDbAzure=Server=tcp:awc-db-server.database.windows.net,1433;Initial Catalog=company-api-db;Persist Security Info=False;User ID=awc-dba;Password=Info99Gum;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30
    ports:
      - "3100:80"
    extra_hosts:
      - "ubuntu-2404:192.168.1.16"
    hostname: "product-api-svc"
    container_name: "product-api-svc"

  web.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Info99Gum
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5259:80"
      - "7125:443"
    extra_hosts:
      - "ubuntu-2404:192.168.1.16"
    hostname: "web-gateway"
    container_name: "web-gateway"
    volumes:
      - ~/.aspnet/https:/https:ro

  webui:
    container_name: "webui"
    extra_hosts:
      - "ubuntu-2404:192.168.1.16"
    ports:
      - "5056:80"    
      - "7126:443"
