# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.

services:
    
  company.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3000        
      - ConnectionStrings__AdventureWorksCycles=Server=tcp:ubuntu-2404,1433;Database=CompanyAPI;User Id=sa;Password=Info99Gum;TrustServerCertificate=True
    ports:
      - "3000:80"
    hostname: "company-api-svc"
    container_name: "company-api-svc"             

  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3001         
      - ConnectionStrings__AdventureWorksCycles=Server=tcp:ubuntu-2404,1433;Database=CompanyAPI;User Id=sa;Password=Info99Gum;TrustServerCertificate=True
    ports:
      - "3001:80"
    hostname: "product-api-svc"
    container_name: "product-api-svc"      

  web.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Info99Gum
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5259:80"
      - "7125:443"
    hostname: "web-gateway"
    container_name: "web-gateway"      
    volumes:
      - ~/.aspnet/https:/https:ro      

