services:

  redis:
    image: redis:latest

  awc.seq:
    image: datalust/seq:latest
    container_name: awc-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80    

  company.api:
    image: brthomasusa/company.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Company/Company.API/Dockerfile
    depends_on:
      - redis      

  product.api:
    image: brthomasusa/product.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Product/Product.API/Dockerfile

  web.gateway:
    image: brthomasusa/web-gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Api.Gateway/Dockerfile
    depends_on:
      - company.api
      - product.api

  webui:
    image: brthomasusa/webui:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebUI/Dockerfile
