services:

  company.api:
    image: company.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Company/Company.API/Dockerfile     

  web.gateway:
    image: web-gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Api.Gateway/Dockerfile     
    depends_on:
      - company.api  
     
     