apiVersion: v1
kind: Pod
metadata:
    name: k8sutils-pod
    namespace: default
spec:
    containers:
      - name: k8sutils
        image: quay.io/iamgini/k8sutils:debian12
        command:
          - sleep
          - "infinity"
        imagePullPolicy: IfNotPresent
        resources:
            requests:
                cpu: 100m
                memory: 100Mi
            limits:
                cpu: 200m
                memory: 200Mi
    restartPolicy: Always
