apiVersion: v1
kind: Pod
metadata:
    name: seq-pod
    labels:
        app: seq
spec:
    containers:
      - name: seq
        image: datalust/seq:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: "ACCEPT_EULA"
            value: "Y"
        resources:
            requests:
                cpu: 100m
                memory: 100Mi
            limits:
                cpu: 500m
                memory: 500Mi
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: seq-svc
spec:
    type: LoadBalancer
    ports:
      - name: seq-dashboard-url
        protocol: TCP
        port: 5341
        targetPort: 80
    selector:
        app: seq
