apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: seq-pvc
    namespace: awc-ns
spec:
    resources:
        requests:
            storage: 2Gi
    accessModes:
      - ReadWriteOnce
    selector:
        matchLabels:
            type: localpath
            env: test
    storageClassName: manual
