apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-deploy
    namespace: awc-ns
spec:
    replicas: 2
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            namespace: awc-ns
            labels:
                app: redis
        spec:
            containers:
              - name: redis-cache
                image: redis:latest
                resources:
                    requests:
                        cpu: "0.5"
                        memory: 100Mi
                    limits:
                        cpu: "1"
                        memory: 300Mi
                ports:
                  - containerPort: 6379
