apiVersion: apps/v1
kind: Deployment
metadata:
    name: webui-deploy
    labels:
        app: webui
spec:
    selector:
        matchLabels:
            app: webui
    replicas: 1
    template:
        metadata:
            labels:
                app: webui
        spec:
            containers:
              - name: webui
                image: brthomasusa/webui:latest
                imagePullPolicy: Always
                resources:
                    requests:
                        cpu: 100m
                        memory: 100Mi
                    limits:
                        cpu: 200m
                        memory: 200Mi
                ports:
                  - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: webui-svc
spec:
    type: LoadBalancer
    ports:
      - port: 5056
        targetPort: 80
    selector:
        app: webui
---


