apiVersion: v1
kind: Service
metadata:
    name: product-api-svc
    namespace: awc-ns
spec:
    ports:
      - name: product-api-url
        protocol: TCP
        port: 3100
        targetPort: 3100
    selector:
        app: product-api
