apiVersion: apps/v1
kind: Deployment
metadata:
    name: product-api
    labels:
        app: product-api
spec:
    selector:
        matchLabels:
            app: product-api
    replicas: 1
    template:
        metadata:
            labels:
                app: product-api
        spec:
            containers:
              - name: product-api
                image: awcacrbrthomasusa.azurecr.io/product-api:latest
                env:
                  - name: "ConnectionStrings__ProductDb"
                    value: "Server=tcp:awc-db-server.database.windows.net,1433;Initial Catalog=product-api-db;Persist Security Info=False;User ID=awc-dba;Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
                  - name: "ASPNETCORE_ENVIRONMENT"
                    value: "Productions"
                  - name: "ASPNETCORE_HTTP_PORTS"
                    value: "3100"
                resources:
                    requests:
                        cpu: 100m
                        memory: 100Mi
                    limits:
                        cpu: 200m
                        memory: 200Mi
                ports:
                  - containerPort: 3100
---
apiVersion: v1
kind: Service
metadata:
    name: product-api
spec:
    ports:
      - port: 3100
    selector:
        app: product-api
---


